version: '3.6'

services:
  peatio:
    image: "rubykube/peatio:2.3.31"
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
    labels: {}
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  arke:
    image: "arke:trade-api"
    env_file:
      - ../config/arke.env
    ports:
      - "8081:8081"
    command: bash -c "bundle exec puma --config config/puma.rb"

  barong:
    image: "rubykube/barong:2.3.24"
    env_file:
      - ../config/barong.env
    ports:
      - "8001:8001"
    volumes:
      - ../config/secrets:/secrets:ro
      - ../config/barong/seeds.yml:/home/app/config/seeds.yml
      - ../config/barong/barong.yml:/home/app/config/barong.yml
      - ../config/barong/authz_rules.yml:/home/app/config/authz_rules.yml
      - ../config/barong/management_api.yml:/home/app/config/management_api.yml

  applogic:
    image: "rubykube/applogic:latest"
    env_file:
      - ../config/applogic.env
    expose:
      - "8081"
    volumes:
      - ../config/applogic/management_api_v2.yml:/home/app/config/management_api_v2.yml
