version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ../config/mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  redis:
    image: redis:4.0.10
    restart: always
    volumes:
      - redis_data:/data


  influxdb:
    image: influxdb:1.7.8
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb
      - ../config/influxdb/build_candles.sql:/build_candles.sql
      - ../config/influxdb/influxdb.sql:/influxdb.sql
    environment:
       INFLUXDB_ADMIN_ENABLED: "true"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: rabbitmq.app.local'
      traefik.port: 15672

  vault:
    image: vault:0.10.2
    restart: always
    volumes:
      - vault_data:/vault
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
  vault_data:
  influx_data:
