version: '3.6'

services:
  proxy:
    image: traefik:1.7.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - www.app.local
          - peatio.app.local
          - ws.ranger.app.local
          - superset.app.local
          - eth.app.local
          - tower.app.local
          - monitor.app.local
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.app.local'
      traefik.port: 8080
